stages:
- build
- release

.template: &env-info
  before_script:
  - env | grep -e CI_COMMIT -e CI_PIPELINE
  - npm  --version
  - yarn --version

test:
  <<: *env-info
  stage: build
  script:
  - make init
  - yarn test

build:
  <<: *env-info
  stage: build
  only:
  - master
  script:
  - make init
  - make build

release:
  <<: *env-info
  stage: release
  when: manual
  script:
  - make release
  - docker login -u kirillt -p $DOCKERHUB_TOKEN
  - docker tag supply-chain-ui wivt/supply-chain-ui:$CI_COMMIT_SHORT_SHA
  - docker tag supply-chain-ui wivt/supply-chain-ui:latest
  - docker push wivt/supply-chain-ui:$CI_COMMIT_SHORT_SHA
  - docker push wivt/supply-chain-ui:latest
